Data Mining Methods to Make Predictions - 3/29/2026 - aprtay2887

In [2]:
# April Taylor
import pandas as pd

df = pd.read_excel("C:\\Files\\Excel\\StudentsPerformance.xlsx")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [4]:
# April Taylor
categorical_cols = [
    "gender", 
    "race/ethnicity",
    "parental level of education",
    "lunch",
    "test preparation course"
]

df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
df_encoded.head()

,math score,reading score,writing score,gender_male,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,parental level of education_bachelor's degree,parental level of education_high school,parental level of education_master's degree,parental level of education_some college,parental level of education_some high school,lunch_standard,test preparation course_none
0,72,72,74,False,True,False,False,False,True,False,False,False,False,True,True
1,69,90,88,False,False,True,False,False,False,False,False,True,False,True,False
2,90,95,93,False,True,False,False,False,False,False,True,False,False,True,True
3,47,57,44,True,False,False,False,False,False,False,False,False,False,False,True
4,76,78,75,True,False,True,False,False,False,False,False,True,False,True,True

In [6]:
# April Taylor

from sklearn.model_selection import train_test_split

X = df_encoded.drop("math score", axis=1)
Y = df_encoded["math score"]

X_train, X_test, Y_train, Y_test = train_test_split( X, Y, test_size=0.20, random_state=42)

In [7]:
# April Taylor

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, Y_train)

LinearRegression()

In [8]:
# April Taylor

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

Y_pred = model.predict(X_test)

mae = mean_absolute_error(Y_test, Y_pred)
mse = mean_squared_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)

mae, mse, r2

(4.214763142474852, 29.095169866715494, 0.8804332983749564)

In [10]:
coef_df = pd.DataFrame({
    "feature": X.columns,
    "coefficient": model.coef_
}).sort_values(by="coefficient", ascending=False)

coef_df

                                          feature  coefficient
2                                     gender_male    13.064884
6                          race/ethnicity_group E     4.892649
12                                 lunch_standard     3.510075
13                   test preparation course_none     3.289642
10       parental level of education_some college     0.998856
8         parental level of education_high school     0.929312
11   parental level of education_some high school     0.756470
1                                   writing score     0.724148
3                          race/ethnicity_group B     0.359323
0                                   reading score     0.236023
5                          race/ethnicity_group D    -0.613236
4                          race/ethnicity_group C    -0.625617
7   parental level of education_bachelor's degree    -0.716901
9     parental level of education_master's degree    -1.400489